### PR TITLE
feat(text-editor): add a text-editor for webui's textarea

### PR DESCRIPTION
**Pull request by M3lkior**
This feature adds an higlith support in textareas when user must fill this areas
with a syntax like XML, JSON or Groovy (For XLST transformation
policy for example)

This feature
- add angular-schema-form-ui-codemirror dependency to allow working with
  codemirror / ui-codemirror and angular-schema-form (use in policies
  schema)
- update codemirror and ui-codemirror versions

### CODE REVIEW

**Comment by NicolasGeraud** [comment]
your PR is not good, see your commits : https://github.com/gravitee-io/gravitee-management-webui/pull/183/commits

you should rebase your branch : 
```
$ git fetch --all
$ git checkout feat/webui-texteditor
$ git rebase origin/master
 # look at your log, you must have only one more commit than origin/master
$ git push --force
```

**Comment by M3lkior** [comment]
It's done ! Sorry.

**Comment by brasseld** [comment]
Closes https://github.com/gravitee-io/issues/issues/69

**Comment by NicolasGeraud** [comment]
fix gravitee-io/issues#147

**Pull request merged**
