### PR TITLE
feat(i18n): add the i18n for brazilian portuguese

### PR DESCRIPTION
**Pull request by alvarollmenezes**
We are studying the possibility of using gravitee as our api gateway and wanted to contribute with the translation to our native language.

It's going to be useful for our users in testing stages and also for future brazilian (or portuguese) users.

As I'm not able to open an issue, I didn't link it to any and commited to master.

### CODE REVIEW

**Comment by brasseld** [comment]
Hi, please create an issue: https://github.com/gravitee-io/issues/issues/new

And associate the commit message to the new issue.

Thanks for your contributions!

**Comment by alvarollmenezes** [comment]
Done. Is it right?

**Comment by alvarollmenezes** [comment]
references gravitee-io/issues#1333

**Comment by brasseld** [comment]
Perfect!

It will be included in 1.18 (12th july).

**Pull request merged**
