### PR TITLE
feat(subscriptions): export

### PR DESCRIPTION
**Pull request by RTabary**
closes gravitee-io/issues#2079

You can see the result on the API's subsciptions page (behind the table)

### CODE REVIEW

**Comment by brasseld** [comment]
Do you think that such feature should be done client-side? (I mean from the UI).
What if the status of a subscription has been changed?

**Comment by romsalto** [comment]
There is maybe a tiny risk for a subscription to change between the click on the export button and the moment the file is generated.
But even if the page was loaded 2 hours ago, when the user clicks on the button the script will get the data from the backend API (not from the page) at this moment to create the file. IMHO there's no more risk doing this way than from backend. 

If it is done on the backend side, other tools plugged to the API could use this feature.

**Comment by romsalto** [comment]
@brasseld Don't worry it's ok 👌! You're surely right for the management side treatment...
I'll check the management's issue and try to do something.

**Comment by brasseld** [comment]
Hey @RTabary 

Any news about this?

**Comment by gaetanmaisse** [comment]
@RTabary I'm closing this PR as it is 2 years old and has a lot of conflicts, feels free to reopen it and comment if you think it is still valuable 🙂 .

**Pull request closed without merging**
