### PR TITLE
Issue/20

### LINKED ISSUE #20: Manage multiple path
We must be able to configure different policies for specific path.
* only api-key policy is mandatory.
* no override capacity
* when creating a new path, we could copy policies from '/' path
* rename '/*' path to '/'
* we could delete path except '/'

### PR DESCRIPTION
**Pull request by NicolasGeraud**
add multi path support for api policies

fix #20

### CODE REVIEW

**Comment by brasseld** [comment]
I must not being able to delete the /* path

**Comment by brasseld** [comment]
It seems that some HTML resources are missing : 
http://localhost:3000/fonts/bootstrap/glyphicons-halflings-regular.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by brasseld** [comment]
When I click on the "stash" icon of a policy from one of defined paths, I don't want to show the form (schema) associated to this policy.

**Comment by NicolasGeraud** [comment]
you must be able to delete /* because this path does not exits anymore. /* is replaced by /

**Comment by brasseld** [comment]
@NicolasGeraud does this mean that root path is now / instead of /* with this PR ?

**Comment by NicolasGeraud** [comment]
yes, because we introduce multipath support, we don't provide (yet) a regex mode to match path.

**Pull request merged**
