### PR TITLE
feat(i18n): Add the i18n for chinese

### PR DESCRIPTION
**Pull request by yang-dw**
closes gravitee-io/issues#1160

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @yang-dw 

Thanks for sharing.
Please create a dedicated issue for this new translation.

**Comment by yang-dw** [comment]
ok, added

Closes gravitee-io/issues#1160

**Comment by yang-dw** [comment]
is now ok? I did't get!

**Comment by brasseld** [comment]
See:

capture d ecran 2018-03-16 a 15 10 34

**Pull request closed without merging**
